# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\"\x1a\n\tBytesList\x12\r\n\x05value\x18\x01 \x03(\x0c\"\x1a\n\tFloatList\x12\r\n\x05value\x18\x01 \x03(\x02\"\x1a\n\tInt64List\x12\r\n\x05value\x18\x01 \x03(\x03\"w\n\x07\x46\x65\x61ture\x12 \n\nbytes_list\x18\x01 \x01(\x0b\x32\n.BytesListH\x00\x12 \n\nfloat_list\x18\x02 \x01(\x0b\x32\n.FloatListH\x00\x12 \n\nint64_list\x18\x03 \x01(\x0b\x32\n.Int64ListH\x00\x42\x06\n\x04kind\"m\n\x08\x46\x65\x61tures\x12\'\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x16.Features.FeatureEntry\x1a\x38\n\x0c\x46\x65\x61tureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Feature:\x02\x38\x01\"&\n\x07\x45xample\x12\x1b\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\t.Featuresb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATURES_FEATUREENTRY']._loaded_options = None
  _globals['_FEATURES_FEATUREENTRY']._serialized_options = b'8\001'
  _globals['_BYTESLIST']._serialized_start=14
  _globals['_BYTESLIST']._serialized_end=40
  _globals['_FLOATLIST']._serialized_start=42
  _globals['_FLOATLIST']._serialized_end=68
  _globals['_INT64LIST']._serialized_start=70
  _globals['_INT64LIST']._serialized_end=96
  _globals['_FEATURE']._serialized_start=98
  _globals['_FEATURE']._serialized_end=217
  _globals['_FEATURES']._serialized_start=219
  _globals['_FEATURES']._serialized_end=328
  _globals['_FEATURES_FEATUREENTRY']._serialized_start=272
  _globals['_FEATURES_FEATUREENTRY']._serialized_end=328
  _globals['_EXAMPLE']._serialized_start=330
  _globals['_EXAMPLE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
