# fly.toml app configuration file generated for mazaryn on 2023-05-24T19:48:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mazaryn"
primary_region = "syd"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "mazaryn.fly.dev"
  PORT = "8080"
  ELIXIR_VERSION = "1.14"
  
[[mounts]]
  source = "mazaryn_data_machines"
  destination = "/app/bin/Mnesia"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
