-record(video, {
    id,
    ai_video_id,
    user_id,
    business_id,
    file_url,
    ipfs_cid,
    thumbnail_cids = [],
    preview_cid,
    original_filename,
    file_size_bytes,
    status,
    original_resolution,
    available_qualities = [],
    codec,
    bitrate,
    frame_rate,
    aspect_ratio,
    title,
    description,
    duration_seconds,
    thumbnail_url,
    thumbnail_timestamp = 0,
    preview_urls = [],
    chapters = [],
    subtitles = [],
    audio_tracks = [],
    interactive_elements = [],
    auto_generated_tags = [],
    detected_objects = [],
    scene_detection = [],
    transcript_cid,
    content_warnings = [],
    views = 0,
    unique_views = 0,
    unique_viewers = [],
    watch_time_total = 0,
    avg_watch_percentage = 0.0,
    likes = [],
    reactions = #{
        like => [],
        love => [],
        wow => [],
        haha => [],
        fire => []
    },
    reaction_counts = #{
        like => 0,
        love => 0,
        wow => 0,
        haha => 0,
        fire => 0
    },
    comments = [],
    shares = 0,
    saves = 0,
    hashtags = [],
    mentions = [],
    location,
    privacy,
    allow_comments = true,
    allow_downloads = false,
    allow_remixes = false,
    monetized = false,
    revenue_model,
    price,
    ad_breaks = [],
    sponsor_info = #{},
    viewer_retention = [],
    geographic_views = #{},
    device_breakdown = #{},
    referral_sources = #{},
    peak_concurrent_viewers = 0,
    is_live = false,
    live_stream_url,
    live_started_at,
    live_ended_at,
    live_viewers_current = 0,
    live_chat_id,
    playlist_ids = [],
    series_id,
    episode_number,
    season_number,
    reported = [],
    moderation_status,
    age_restriction,
    pin_info,
    cdn_urls = #{},
    peer_availability = [],
    date_created,
    date_updated,
    date_published,
    last_viewed,
    upload_device_info,
    processing_time_ms,
    video_embedding,
    visual_signature,
    sign_language_overlay_cid,
    audio_description_cid,
    accessibility_score,
    vertical_version_cid,
    square_version_cid,
    story_version_cid,
    format_variants = #{},
    collaboration_tree = [],
    remix_parent_id,
    remix_children_ids = [],
    remix_permissions = #{},
    collaboration_revenue_split = [],
    adaptive_bitrate_manifest,
    buffer_health_metrics = [],
    stream_protocol,
    drm_info = #{},
    offline_download_cid,
    filming_equipment = #{},
    color_grading_lut_cid,
    behind_the_scenes_cid,
    production_notes = [],
    predicted_virality_score,
    optimal_posting_time,
    suggested_improvements = [],
    ab_test_variants = [],
    nft_minted = false,
    nft_contract_address,
    nft_token_id,
    nft_metadata_cid,
    blockchain_proof_cid,
    limited_edition_count,
    semantic_search_keywords = [],
    visual_search_embeddings = [],
    audio_fingerprint_segments = [],
    multimodal_search_index = #{},
    interactive_hotspots = [],
    branching_narrative_tree,
    live_poll_results = #{},
    gamification_elements = [],
    synchronized_viewing_rooms = [],
    stream_category,
    stream_tags = [],
    raid_enabled = true,
    raid_target_channel,
    raid_viewer_count,
    host_enabled = true,
    hosted_channels = [],
    subscriber_only_mode = false,
    subscriber_tiers = [],
    subscriber_count = 0,
    subscriber_badges = #{},
    emote_library = [],
    bits_enabled = true,
    bits_received = 0,
    donation_alerts = [],
    donation_goals = [],
    top_donors = [],
    moderators = [],
    vips = [],
    chat_rules = [],
    banned_words = [],
    slow_mode = false,
    slow_mode_duration = 0,
    subscriber_only_chat = false,
    follower_only_chat = false,
    follower_only_duration = 0,
    emote_only_mode = false,
    channel_points_enabled = true,
    point_rewards = [],
    points_distributed = 0,
    custom_rewards_redeemed = [],
    clips_enabled = true,
    user_generated_clips = [],
    trending_clips = [],
    clip_of_the_week,
    auto_highlight_moments = [],
    simulcast_destinations = [],
    cross_platform_chat = false,
    unified_chat_id,
    is_short_form = false,
    loop_count = 0,
    average_loop_percentage,
    sound_id,
    sound_usage_count = 0,
    duet_enabled = true,
    duet_videos = [],
    stitch_enabled = true,
    stitch_videos = [],
    original_audio_cid,
    effects_used = [],
    filters_applied = [],
    green_screen_enabled = false,
    ar_effects = [],
    trending_score = 0.0,
    fyp_appearances = 0,
    sound_trending = false,
    hashtag_trending = [],
    challenge_id,
    text_overlays = [],
    voiceover_cid,
    speed_adjustments = [],
    transitions = [],
    stickers = [],
    share_to_story_count = 0,
    profile_views_from_video = 0,
    follower_conversion_rate,
    rewatches = 0,
    analytics_insights = #{},
    audience_similar_accounts = [],
    content_inspiration = [],
    best_time_to_post,
    commercial_music_license = false,
    music_attribution_required = false,
    original_content_certified = false,
    copyright_claims = [],
    watch_pattern_signature,
    retention_breakpoints = [],
    optimal_thumbnail_frame,
    hook_effectiveness_score,
    data = #{}
}).

-record(music, {
    id,
    ai_music_id,
    user_id,
    business_id,
    artist_id,
    file_url,
    ipfs_cid,
    original_filename,
    file_size_bytes,
    status,
    format,
    bitrate,
    sample_rate,
    channels,
    available_qualities = [],
    title,
    artist,
    featured_artists = [],
    album,
    album_id,
    album_art_cid,
    album_art_url,
    duration_seconds,
    genre = [],
    sub_genre = [],
    mood = [],
    tempo_bpm,
    key,
    time_signature,
    composer = [],
    lyricist = [],
    producer = [],
    label,
    isrc,
    upc,
    copyright_info,
    license_type,
    lyrics_cid,
    lyrics_synced = [],
    has_explicit_content = false,
    language,
    waveform_cid,
    spectrum_analysis_cid,
    peaks_data = [],
    audio_fingerprint,
    detected_instruments = [],
    vocal_presence = false,
    energy_level,
    danceability,
    acousticness,
    instrumentalness,
    auto_generated_tags = [],
    plays = 0,
    unique_listeners = 0,
    listen_time_total = 0,
    completion_rate = 0.0,
    likes = [],
    reactions = #{
        love => [],
        fire => [],
        sad => [],
        party => [],
        vibe => []
    },
    reaction_counts = #{
        love => 0,
        fire => 0,
        sad => 0,
        party => 0,
        vibe => 0
    },
    comments = [],
    shares = 0,
    saves = 0,
    added_to_playlists = 0,
    hashtags = [],
    mentions = [],
    collaborators = [],
    privacy,
    allow_comments = true,
    allow_downloads = false,
    allow_remixes = false,
    playlist_ids = [],
    track_number,
    disc_number,
    total_tracks,
    monetized = false,
    revenue_model,
    price_download,
    price_stream_per_play,
    streaming_royalties = #{},
    skip_rate = 0.0,
    replay_count = 0,
    geographic_plays = #{},
    device_breakdown = #{},
    referral_sources = #{},
    peak_concurrent_listeners = 0,
    listening_hours = [],
    similar_tracks = [],
    radio_seed_weight,
    discovery_score,
    live_recording = false,
    concert_date,
    venue,
    original_track_id,
    remix_type,
    remixes = [],
    versions = [],
    reported = [],
    moderation_status,
    age_restriction,
    content_warnings = [],
    pin_info,
    cdn_urls = #{},
    peer_availability = [],
    release_date,
    release_type,
    pre_release = false,
    premiere_timestamp,
    date_created,
    date_updated,
    date_published,
    last_played,
    upload_device_info,
    processing_time_ms,
    spatial_audio_cid,
    binaural_audio_cid,
    immersive_format,
    head_tracking_data,
    separated_stems_cids = #{},
    stem_quality_score,
    remix_template_cid,
    midi_file_cid,
    chord_progression = [],
    audio_embedding,
    musical_structure = [],
    harmonic_complexity_score,
    vocal_melody_cid,
    rhythm_pattern_signature,
    collaboration_sessions = [],
    multitrack_project_cid,
    version_history = [],
    contributor_credits = [],
    royalty_split_smart_contract,
    live_performance_recordings = [],
    setlist_context,
    concert_sync_id,
    live_jam_session_id,
    virtual_concert_cid,
    sample_clearances = [],
    mechanical_license_info,
    sync_licensing_available = true,
    territorial_rights = #{},
    creative_commons_derivative_tree = [],
    blockchain_rights_token,
    sonic_signature,
    influence_tags = [],
    era_classification,
    cultural_context = [],
    listening_context_scores = #{},
    crossover_potential,
    adaptive_layers_cids = #{},
    interactive_mixing_params,
    generative_rules,
    loop_points = [],
    branching_sections = [],
    lufs_integrated,
    dynamic_range,
    true_peak_db,
    mastering_chain = [],
    reference_tracks = [],
    mastering_engineer,
    remaster_versions = [],
    fan_tier_access = #{},
    early_access_until,
    limited_edition_vinyl_link,
    fan_token_gated = false,
    community_remix_challenge_id,
    behind_the_music_cid,
    producer_commentary_cid,
    exclusive_listening_parties = [],
    radio_seed_enabled = true,
    included_in_playlists = [],
    playlist_reach = 0,
    editorial_playlist_picks = [],
    user_taste_match = #{},
    blend_compatibility_score,
    vibe_tags = [],
    time_of_day_affinity = #{},
    friend_activity = [],
    collaborative_playlists = [],
    queue_additions = 0,
    viral_charts_position = [],
    new_music_friday_featured = false,
    release_radar_appearances = 0,
    discover_weekly_appearances = 0,
    monthly_listeners_trend = [],
    listener_demographics = #{},
    fan_concentration = #{},
    top_cities = [],
    playlist_conversion_rate,
    skip_30sec_rate,
    save_rate,
    playlist_add_rate,
    share_rate,
    reposts = [],
    repost_count = 0,
    spotlight_tracks = [],
    timed_comments = [],
    comment_heatmap = [],
    download_enabled = false,
    download_count = 0,
    downloadable_formats = [],
    private_share_links = [],
    scheduled_release,
    secret_link,
    fan_powered_royalties = false,
    tip_jar_enabled = false,
    tips_received = [],
    pro_unlimited_tier = false,
    waveform_comments_enabled = true,
    waveform_color,
    waveform_style,
    seekable_waveform_cid,
    replace_file_history = [],
    mastered_on_soundcloud = false,
    plays_per_country = #{},
    plays_per_source = #{},
    embedded_plays = 0,
    lossless_available = false,
    lossless_cid,
    hi_res_lossless = false,
    hi_res_cid,
    audio_quality_tier,
    dolby_atmos_available = false,
    dolby_atmos_cid,
    apple_digital_master = false,
    time_synced_lyrics = [],
    lyrics_language_versions = #{},
    lyrics_translation = #{},
    sing_along_mode = false,
    apple_music_1_plays = 0,
    station_appearances = [],
    dj_mentions = [],
    apple_music_editor_notes,
    curator_picks = [],
    essential_album = false,
    music_video_id,
    video_available = false,
    behind_the_lyrics_video,
    composer_details = #{},
    conductor,
    orchestra,
    movement_number,
    work_id,
    catalog_number,
    shazam_count = 0,
    shazam_trending = false,
    shazam_discovery_rank,
    optimal_crossfade_point,
    gapless_playback = false,
    crossfade_duration = 0,
    ai_extended_version_cid,
    ai_radio_edit_cid,
    ai_instrumental_cid,
    ai_acapella_cid,
    ai_8d_audio_cid,
    transition_compatibility = #{},
    bpm_locked = false,
    harmonic_mixing_key,
    energy_curve = [],
    first_listeners_club = [],
    superfan_unlocks = [],
    listening_milestones = #{},
    fan_challenges = [],
    open_verse_enabled = false,
    stem_remix_competition_id,
    community_cover_versions = [],
    listener_journey_map = [],
    retention_by_segment = [],
    viral_coefficient,
    playlist_velocity,
    tiktok_usage_count = 0,
    instagram_story_usage = 0,
    youtube_shorts_usage = 0,
    viral_moment_timestamp,
    data = #{}
}).

-record(album, {
    id,
    title,
    artist,
    artist_id,
    album_art_cid,
    album_art_url,
    release_date,
    genre = [],
    description,
    label,
    upc,
    track_ids = [],
    total_duration,
    type,
    likes = [],
    saves = 0,
    plays_total = 0,
    date_created,
    data = #{}
}).

-record(playlist, {
    id,
    creator_id,
    title,
    description,
    cover_image_cid,
    cover_image_url,
    track_ids = [],
    video_ids = [],
    type,
    privacy,
    collaborative = false,
    collaborators = [],
    followers = [],
    likes = [],
    plays = 0,
    total_duration,
    mood_tags = [],
    auto_generated = false,
    date_created,
    date_updated,
    data = #{}
}).

-record(artist, {
    id,
    user_id,
    stage_name,
    bio,
    profile_image_cid,
    banner_image_cid,
    verified = false,
    genres = [],
    social_links = #{},
    monthly_listeners = 0,
    total_plays = 0,
    followers = [],
    top_tracks = [],
    albums = [],
    singles = [],
    collaborations = [],
    date_created,
    data = #{}
}).

-record(media_analytics, {
    media_id,
    media_type,
    date,
    views = 0,
    unique_viewers = 0,
    watch_time = 0,
    avg_watch_percentage = 0.0,
    likes = 0,
    comments = 0,
    shares = 0,
    geographic_breakdown = #{},
    device_breakdown = #{},
    data = #{}
}).

-record(audio_stem, {
    id,
    music_id,
    stem_type,
    ipfs_cid,
    quality,
    isolation_score,
    processing_algorithm,
    file_size_bytes,
    format,
    sample_rate,
    date_created,
    data = #{}
}).

-record(remix_project, {
    id,
    original_track_id,
    remixer_id,
    project_name,
    remix_type,
    stems_used = [],
    project_file_cid,
    status,
    collaboration_mode,
    contributors = [],
    bpm_change,
    key_change,
    added_elements = [],
    date_created,
    date_submitted,
    date_published,
    data = #{}
}).

-record(series, {
    id,
    creator_id,
    title,
    description,
    banner_cid,
    thumbnail_cid,
    category,
    seasons = [],
    total_episodes = 0,
    total_views = 0,
    subscribers = [],
    release_schedule,
    next_episode_date,
    trailer_video_id,
    featured = false,
    date_created,
    data = #{}
}).

-record(season, {
    id,
    series_id,
    season_number,
    title,
    description,
    episode_ids = [],
    release_date,
    trailer_video_id,
    data = #{}
}).

-record(content_analytics_realtime, {
    content_id,
    content_type,
    timestamp,
    active_viewers = 0,
    active_listeners = 0,
    concurrent_peak = 0,
    engagement_rate,
    avg_watch_time_seconds,
    geographic_heatmap = #{},
    trending_score,
    velocity,
    data = #{}
}).

-record(creator_analytics, {
    creator_id,
    period,
    period_start,
    period_end,
    total_views = 0,
    total_watch_time = 0,
    total_plays = 0,
    total_listen_time = 0,
    subscriber_growth = 0,
    follower_growth = 0,
    avg_engagement_rate,
    top_performing_content = [],
    viral_content = [],
    trending_hashtags = [],
    audience_demographics = #{},
    audience_retention_curve = [],
    audience_growth_sources = #{},
    top_geographic_regions = [],
    total_revenue = 0.0,
    revenue_by_source = #{},
    projected_revenue,
    best_posting_times = [],
    content_type_performance = #{},
    suggested_optimizations = [],
    data = #{}
}).

-record(video_hotspot, {
    id,
    video_id,
    timestamp,
    duration,
    position = #{},
    hotspot_type,
    content = #{},
    click_count = 0,
    conversion_rate = 0.0,
    data = #{}
}).

-record(interactive_poll, {
    id,
    video_id,
    music_id,
    timestamp,
    question,
    options = [],
    total_votes = 0,
    results_visible = true,
    closes_at,
    data = #{}
}).

-record(media_nft, {
    id,
    media_id,
    media_type,
    creator_id,
    blockchain,
    contract_address,
    token_id,
    token_standard,
    edition_number,
    total_editions,
    rarity_tier,
    metadata_cid,
    attributes = [],
    unlockable_content_cid,
    current_owner,
    mint_price,
    current_price,
    last_sale_price,
    royalty_percentage,
    trading_history = [],
    access_benefits = [],
    expiration_date,
    date_minted,
    data = #{}
}).

-record(spatial_audio_metadata, {
    id,
    music_id,
    video_id,
    format,
    object_count,
    channel_layout,
    audio_objects = [],
    head_tracking_required = false,
    room_calibration_data,
    renderer_settings = #{},
    fallback_stereo_cid,
    spatial_resolution,
    spatial_accuracy_score,
    date_created,
    data = #{}
}).

-record(recommendation_profile, {
    user_id,
    video_preference_embedding,
    music_preference_embedding,
    watched_videos = [],
    listened_tracks = [],
    genre_affinity = #{},
    mood_preferences = #{},
    peak_activity_times = [],
    avg_session_duration,
    binge_watching_tendency,
    discovery_vs_familiar_ratio,
    followed_creators = [],
    similar_users = [],
    predicted_interests = [],
    churn_risk_score,
    lifetime_value_estimate,
    last_updated,
    data = #{}
}).

-record(live_stream, {
    id,
    video_id,
    streamer_id,
    stream_key,
    ingest_url,
    playback_url,
    backup_stream_url,
    protocol,
    bitrate_current,
    resolution_current,
    latency_mode,
    status,
    scheduled_start,
    actual_start,
    ended_at,
    current_viewers = 0,
    peak_viewers = 0,
    total_unique_viewers = 0,
    viewer_timeline = [],
    chat_id,
    polls_active = [],
    donations_enabled = true,
    super_chat_messages = [],
    simulcast_platforms = [],
    auto_record = true,
    recording_cid,
    highlights = [],
    subscription_only = false,
    ticket_price,
    donations_total = 0.0,
    dropped_frames = 0,
    avg_latency_ms,
    connection_quality,
    data = #{}
}).

-record(collab_session, {
    id,
    session_name,
    host_id,
    participants = [],
    project_type,
    base_track_id,
    working_track_cid,
    active_now = false,
    bpm,
    key,
    metronome_enabled = true,
    tracks = [],
    chat_log = [],
    version_snapshots = [],
    scheduled_sessions = [],
    total_session_time = 0,
    final_mix_cid,
    published_track_id,
    date_created,
    last_active,
    data = #{}
}).

-record(viral_challenge, {
    id,
    challenge_name,
    creator_id,
    hashtag,
    description,
    sound_id,
    participant_count = 0,
    video_submissions = [],
    total_views = 0,
    trending_score,
    start_date,
    end_date,
    prizes = [],
    featured_submissions = [],
    rules,
    data = #{}
}).

-record(sound_snippet, {
    id,
    name,
    artist,
    original_video_id,
    original_music_id,
    audio_cid,
    duration_seconds,
    usage_count = 0,
    trending = false,
    category,
    favorites = 0,
    created_by,
    date_created,
    data = #{}
}).

-record(channel_points, {
    channel_id,
    user_id,
    points_balance = 0,
    points_lifetime = 0,
    watch_time_points = 10,
    subscription_multiplier = 2.0,
    redemption_history = [],
    data = #{}
}).

-record(channel_reward, {
    id,
    channel_id,
    reward_name,
    description,
    cost,
    reward_type,
    cooldown_seconds = 0,
    max_per_stream,
    max_per_user_per_stream,
    available = true,
    redemption_count = 0,
    custom_action,
    data = #{}
}).

-record(smart_playlist, {
    id,
    name,
    creator_id,
    rules = [],
    auto_update = true,
    max_tracks = 50,
    seed_tracks = [],
    mood_target,
    energy_range = {0.0, 1.0},
    tempo_range,
    genre_mix = #{},
    user_taste_weight = 0.5,
    recency_bias = 0.3,
    popularity_range,
    refresh_frequency,
    last_updated,
    track_turnover_rate,
    data = #{}
}).

-record(timed_comment, {
    id,
    music_id,
    video_id,
    user_id,
    comment_text,
    timestamp_ms,
    likes = [],
    replies = [],
    date_created,
    data = #{}
}).

-record(curator, {
    id,
    name,
    bio,
    avatar_cid,
    curator_type,
    verified = false,
    playlists_curated = [],
    total_followers = 0,
    editor_notes_style,
    specialization = [],
    playlist_reach = 0,
    track_discovery_count = 0,
    data = #{}
}).

-record(sound_usage, {
    id,
    sound_id,
    music_id,
    platform,
    video_url,
    creator_id,
    usage_date,
    views = 0,
    engagement_score,
    viral = false,
    data = #{}
}).

-record(listener_journey, {
    user_id,
    music_id,
    discovery_source,
    discovery_context,
    discovery_timestamp,
    first_play_duration,
    plays_until_save,
    plays_until_playlist_add,
    total_plays = 0,
    skip_points = [],
    replay_sections = [],
    listening_sessions = [],
    became_fan = false,
    shared = false,
    influenced_others = [],
    data = #{}
}).

-record(stream_raid, {
    id,
    source_stream_id,
    target_stream_id,
    raider_id,
    raided_id,
    viewer_count,
    raid_timestamp,
    raid_message,
    accepted = false,
    viewers_retained,
    data = #{}
}).

-record(video_clip, {
    id,
    source_video_id,
    source_stream_id,
    creator_id,
    title,
    start_timestamp,
    end_timestamp,
    duration,
    clip_cid,
    thumbnail_cid,
    views = 0,
    shares = 0,
    likes = [],
    game_category,
    tags = [],
    featured = false,
    viral_score,
    trending = false,
    date_created,
    data = #{}
}).

-record(stem_listing, {
    id,
    music_id,
    seller_id,
    stems_included = [],
    stem_cids = #{},
    price,
    license_type,
    usage_rights = [],
    purchases = 0,
    revenue = 0.0,
    stem_quality_verified = false,
    sample_previews = #{},
    data = #{}
}).

-record(ai_video, {
    id,
    video_id,
    date_created
}).

-record(media_view, {
    id,
    media_id,
    media_type,
    user_id,
    view_duration,
    completion_percentage,
    date_viewed,
    device_info,
    location,
    referral_source,
    data = #{}
}).

-record(livestream, {
    id,
    user_id,
    title,
    description,
    thumbnail_cid,
    preview_cids = [],
    status,
    visibility,
    tags = [],
    category,
    language = "en",
    stream_key,
    rtmp_url,
    rtmp_backup_url,
    playback_url,
    hls_url,
    dash_url,
    rust_stream_id,
    protocol = rtmp,
    latency_mode = normal,
    viewers_count = 0,
    peak_viewers = 0,
    total_unique_viewers = 0,
    unique_viewers = [],
    viewer_timeline = [],
    current_bitrate = 0,
    current_resolution,
    target_bitrate = 5000000,
    target_resolution = "1920x1080",
    stream_quality_score = 0.0,
    dropped_frames = 0,
    connection_quality = stable,
    chat_enabled = true,
    chat_mode = normal,
    chat_messages = [],
    emote_only_mode = false,
    subscriber_only_chat = false,
    follower_only_chat = false,
    follower_only_duration = 0,
    slow_mode = false,
    slow_mode_duration = 0,
    banned_words = [],
    chat_rules = [],
    moderators = [],
    vips = [],
    banned_users = [],
    reactions = #{
        like => [],
        love => [],
        wow => [],
        haha => [],
        fire => []
    },
    reaction_counts = #{
        like => 0,
        love => 0,
        wow => 0,
        haha => 0,
        fire => 0
    },
    shares = 0,
    saves = 0,
    scheduled_for,
    started_at,
    ended_at,
    duration_seconds = 0,
    auto_record = true,
    recording_cid,
    recording_status = disabled,
    vod_enabled = true,
    vod_cid,
    clips_enabled = true,
    user_generated_clips = [],
    highlights = [],
    auto_highlight_moments = [],
    donations_enabled = true,
    donation_alerts = [],
    donation_goals = [],
    donations_total = 0.0,
    top_donors = [],
    bits_enabled = true,
    bits_received = 0,
    super_chat_enabled = true,
    super_chat_messages = [],
    channel_points_enabled = true,
    point_rewards = [],
    custom_rewards_redeemed = [],
    subscriber_only_mode = false,
    subscriber_tiers = [],
    subscriber_count = 0,
    subscriber_badges = #{},
    raid_enabled = true,
    raid_source_stream_id,
    raid_target_stream_id,
    raid_viewer_count = 0,
    host_enabled = true,
    hosted_channels = [],
    simulcast_enabled = false,
    simulcast_destinations = [],
    simulcast_platforms = [],
    cross_platform_chat = false,
    interactive_elements = [],
    polls_active = [],
    interactive_hotspots = [],
    gamification_elements = [],
    achievements = [],
    adaptive_bitrate_enabled = true,
    adaptive_bitrate_manifest,
    buffer_health_metrics = [],
    stream_health_score = 100.0,
    encoding_settings = #{},
    transcoding_profiles = [],
    dvr_enabled = false,
    dvr_window_seconds = 7200,
    low_latency_enabled = false,
    ultra_low_latency = false,
    cdn_urls = #{},
    edge_servers = [],
    multicast_enabled = false,
    p2p_enabled = false,
    peer_availability = [],
    geo_restrictions = [],
    age_restriction,
    content_warnings = [],
    mature_content = false,
    monetized = false,
    revenue_model,
    price_per_view,
    pay_per_view = false,
    subscription_required = false,
    ad_breaks_enabled = true,
    ad_break_timestamps = [],
    sponsor_info = #{},
    sponsored_stream = false,
    analytics_enabled = true,
    viewer_retention = [],
    engagement_rate = 0.0,
    chat_activity_rate = 0.0,
    geographic_views = #{},
    device_breakdown = #{},
    referral_sources = #{},
    peak_concurrent_viewers_timestamp,
    avg_watch_duration = 0.0,
    completion_rate = 0.0,
    return_viewer_rate = 0.0,
    new_follower_count = 0,
    new_subscriber_count = 0,
    clips_created_during_stream = 0,
    viral_moments = [],
    trending_score = 0.0,
    discovery_score = 0.0,
    recommended_to = [],
    featured = false,
    featured_until,
    platform_promoted = false,
    collab_mode = false,
    collaboration_participants = [],
    multi_stream_enabled = false,
    co_streamers = [],
    split_screen_layout,
    picture_in_picture = false,
    screen_share_enabled = true,
    webcam_enabled = true,
    audio_only_mode = false,
    spatial_audio = false,
    binaural_audio = false,
    audio_quality = high,
    video_filters = [],
    effects_used = [],
    overlays = [],
    custom_graphics = [],
    green_screen_enabled = false,
    background_replacement_cid,
    virtual_background = false,
    ar_effects = [],
    face_tracking = false,
    auto_framing = false,
    noise_suppression = true,
    echo_cancellation = true,
    auto_volume = true,
    accessibility_features = #{},
    closed_captions_enabled = false,
    auto_captions = false,
    caption_language = "en",
    sign_language_interpreter = false,
    audio_description = false,
    high_contrast_mode = false,
    metadata_tags = [],
    searchable_keywords = [],
    seo_optimized = false,
    thumbnail_ab_test = false,
    title_ab_test = false,
    notification_sent = false,
    notification_sent_to = [],
    push_notifications_count = 0,
    email_notifications_count = 0,
    scheduled_reminders = [],
    countdown_enabled = false,
    countdown_duration = 0,
    pre_stream_lobby = false,
    post_stream_screen = false,
    end_screen_cid,
    replay_available = true,
    replay_cid,
    vod_available_until,
    auto_delete_after = 0,
    archive_enabled = false,
    archive_cid,
    nft_minted = false,
    nft_contract_address,
    nft_token_id,
    nft_metadata_cid,
    blockchain_proof_cid,
    token_gated = false,
    token_requirement,
    fan_tier_access = #{},
    early_access_enabled = false,
    exclusive_for_members = false,
    community_only = false,
    stream_series_id,
    episode_number,
    season_number,
    recurring_schedule,
    next_stream_date,
    stream_template_id,
    brand_partnership = false,
    brand_partner_info = #{},
    product_placement = [],
    affiliate_links = [],
    merchandise_showcase = [],
    reported = [],
    moderation_status,
    ai_moderation_enabled = true,
    auto_ban_enabled = false,
    toxicity_filter_level = medium,
    sentiment_analysis = #{},
    stream_title_changes = [],
    category_changes = [],
    quality_changes_log = [],
    technical_issues_log = [],
    viewer_feedback = [],
    polls_results = [],
    quiz_results = [],
    predictions = [],
    prediction_results = [],
    betting_enabled = false,
    watch_parties = [],
    synchronized_viewing_rooms = [],
    virtual_theater_mode = false,
    watch_together_enabled = false,
    reaction_videos = [],
    duet_enabled = false,
    stitch_enabled = false,
    remix_enabled = false,
    clip_of_stream_winner,
    mvp_viewer,
    most_active_chatter,
    biggest_donor,
    loyalty_points_distributed = 0,
    xp_earned_by_viewers = #{},
    achievements_unlocked = [],
    leaderboard_position,
    competitive_ranking,
    esports_tournament = false,
    tournament_info = #{},
    match_id,
    game_being_played,
    game_metadata = #{},
    stream_companion_app = false,
    second_screen_experience = false,
    mobile_companion_features = [],
    api_webhooks = [],
    integration_enabled = [],
    third_party_bots = [],
    stream_deck_integration = false,
    obs_plugin_active = false,
    streamlabs_connected = false,
    automated_scenes = [],
    scene_transitions = [],
    production_quality_score = 0.0,
    professional_setup = false,
    studio_mode = false,
    multi_camera_setup = false,
    camera_angles = [],
    instant_replay_available = false,
    slow_motion_capable = false,
    time_travel_enabled = false,
    dvr_controls = #{},
    emergency_backup_stream,
    failover_enabled = false,
    redundancy_servers = [],
    uptime_percentage = 100.0,
    connection_drops = 0,
    reconnection_attempts = 0,
    stream_stability_score = 100.0,
    optimal_settings_applied = false,
    bandwidth_test_results = #{},
    network_conditions = stable,
    isp_info,
    server_location,
    optimal_ingest_server,
    custom_rtmp_server,
    rtmps_enabled = false,
    srt_enabled = false,
    webrtc_enabled = false,
    stream_protocol_version,
    encryption_enabled = false,
    drm_protected = false,
    watermark_enabled = false,
    watermark_cid,
    copyright_music_detected = [],
    copyright_claims = [],
    dmca_safe = true,
    royalty_free_music = [],
    licensed_music = [],
    music_attribution = [],
    original_content_certified = false,
    verification_badge = false,
    partner_status = false,
    affiliate_status = false,
    creator_tier,
    follower_milestone_reached = [],
    subscriber_milestone_reached = [],
    view_milestone_reached = [],
    stream_anniversary = false,
    special_events = [],
    charity_stream = false,
    charity_info = #{},
    fundraising_goal,
    amount_raised = 0.0,
    donation_matching = false,
    collaboration_tree = [],
    guest_appearances = [],
    interview_mode = false,
    podcast_mode = false,
    educational_content = false,
    tutorial_stream = false,
    workshop_stream = false,
    qa_session = false,
    ama_mode = false,
    behind_the_scenes = false,
    irl_stream = false,
    outdoor_stream = false,
    mobile_streaming = false,
    travel_stream = false,
    location_tagging = [],
    gps_coordinates,
    venue_info,
    event_coverage = false,
    event_name,
    festival_stream = false,
    concert_stream = false,
    sports_event = false,
    breaking_news = false,
    live_journalism = false,
    documentary_stream = false,
    creative_stream = false,
    art_stream = false,
    music_production = false,
    coding_stream = false,
    science_stream = false,
    educational_institution,
    lecture_stream = false,
    webinar_mode = false,
    conference_stream = false,
    meetup_stream = false,
    networking_enabled = false,
    business_stream = false,
    product_launch = false,
    demo_stream = false,
    sales_pitch = false,
    investor_presentation = false,
    earnings_call = false,
    corporate_event = false,
    training_session = false,
    onboarding_stream = false,
    customer_support_stream = false,
    fitness_stream = false,
    workout_session = false,
    yoga_class = false,
    meditation_session = false,
    cooking_show = false,
    recipe_demo = false,
    food_review = false,
    restaurant_tour = false,
    travel_vlog = false,
    house_tour = false,
    shopping_haul = false,
    unboxing_stream = false,
    product_review = false,
    tech_review = false,
    gadget_showcase = false,
    asmr_stream = false,
    relaxation_stream = false,
    ambient_stream = false,
    lofi_stream = false,
    music_performance = false,
    dj_set = false,
    karaoke_stream = false,
    talent_show = false,
    competition_stream = false,
    reality_show = false,
    game_show = false,
    trivia_night = false,
    bingo_game = false,
    casino_stream = false,
    poker_tournament = false,
    speedrunning = false,
    esports_match = false,
    tournament_bracket,
    team_vs_team = false,
    pvp_match = false,
    raid_party = false,
    dungeon_run = false,
    boss_fight = false,
    world_first_attempt = false,
    challenge_run = false,
    hardcore_mode = false,
    permadeath_run = false,
    randomizer_run = false,
    mod_showcase = false,
    custom_map = false,
    user_generated_content = false,
    community_creations = [],
    fan_art_showcase = [],
    meme_review = false,
    reaction_stream = false,
    watchalong_stream = false,
    movie_night = false,
    tv_show_discussion = false,
    anime_watchparty = false,
    sports_commentary = false,
    news_commentary = false,
    political_discussion = false,
    debate_stream = false,
    panel_discussion = false,
    roundtable = false,
    interview_series = false,
    podcast_recording = false,
    radio_show = false,
    talk_show = false,
    late_night_stream = false,
    morning_show = false,
    daily_digest = false,
    weekly_recap = false,
    monthly_roundup = false,
    year_in_review = false,
    anniversary_special = false,
    milestone_celebration = false,
    comeback_stream = false,
    farewell_stream = false,
    final_stream = false,
    hiatus_announcement = false,
    return_stream = false,
    rebrand_reveal = false,
    new_look = false,
    setup_tour = false,
    gear_review = false,
    tips_and_tricks = false,
    how_to_stream = false,
    meta_stream = false,
    stream_about_streaming = false,
    blooper_reel = false,
    outtakes = false,
    deleted_scenes = false,
    extended_cut = false,
    directors_cut = false,
    uncut_version = false,
    raw_footage = false,
    alternate_angles = [],
    bonus_content_cid,
    exclusive_content_cid,
    members_only_content = false,
    premium_tier_only = false,
    date_created,
    data = #{}
}).
