%% TODO: change id order for testing, modify later
-record(user, { id, 
                ai_user_id,
                business_id = [],
                ads_id = [],
                username,
                password,
                email,
                address,
                knode = [],
                media = [],
                post = [],
                blog_post = [],
                notif = [],
                following = [],
                follower = [],
                blocked = [],
                saved_posts = [],
                other_info = [], %location, birthday
                private = false,
                date_created,
                date_updated,
                avatar_url,
                banner_url,
                token_id,
                chat = [],
                verified = false,
                report = [],
                level, % Includes 20 Levels based on User Activity
                last_activity,
                suspend = [],
                data = #{} }). 


-record(notif, { id,
                 follower,
                 user_id,
                 message,
                 date_created,
                 data = #{} }).

-record(post, { id,
                ai_post_id,
                content,
                emoji = [],
                comments = [],
                likes = [],
                media = [],
                hashtag = [],
                mention,
                link_url,
                author,
                other = [],
                date_created,
                date_updated,
                report = [],
                data = #{} }). 


-record(blog_post, {id, 
                    content,
                    comments = [],
                    media,
                    author,
                    date_created,
                    date_updated,
                    data = #{} }).

-record(comment, {id,
                  post,
                  author,
                  content,
                  date_created,
                  data = #{} }).

-record(blog_comment, {id,
                       blog_post,
                       author, 
                       content,
                       date_created,
                       data = #{} }).

-record(like, {id,
               post,
               userID,
               date_created,
               data = #{} }).

-record(chat, {id, 
               ai_chat_id,
               user_id,
               recipient_id,
               body,
               media = [],
               bot,
               date_created,
               date_updated,
               data = #{} }).


-record(event, {name, date, loc, desc, data = #{} }).
-record(follower, {id, username, data = #{}}).
-record(following, {id, username, data = #{} }).
-record(hed_wallet, { id, password, date_created, data =#{} }).

-record(media, {id, ai_media_id, user_id, file, files, type,
date_created, date_updated, report = [], data = #{}}). 
-record(suspend, {
    id,
    user,
    status = false,
    date_created,
    duration
}).
-record(report, {
    id,
    type,
    description,
    reporter,
    user,
    post,
    media,
    date_created,
    data = #{}
}).

-record(ai_user, {
    id,
    user_id,
    interests = [],             % List of user interests (e.g., [sports, music, art])
    behavior_tags = [],         % Tags representing user behavior patterns (e.g., [active, frequent])
    interaction_history = [],       % History of interactions with other users and content (e.g., [{timestamp, interaction_type}])
    device_info = [],               % Information about devices used by the user (e.g., [{device_type, os_version}])
    language_preferences = [],      % List of languages preferred by the user (e.g., [en, es]) 
    active_times = [],          % Times of day when the user is most active (e.g., [{0, 6}, {6, 12}, {12, 18}, {18, 24}])
    user_segments = [],             % Segments or groups the user belongs to (e.g., [premium, beta_tester])
    ai_generated_recommendations = [], % Recommendations generated by AI (e.g., [{recommendation_id, recommendation_details}])
    ab_test_groups = [],            % Groups for A/B testing (e.g., [group_a, group_b])
    gdpr_consent_log = [],           % Log of GDPR consent actions and preferences (e.g., [{timestamp, consent_type}])
    sentiment_scores = #{},         % Key-value pairs of sentiment scores (e.g., #{positive => 75, negative => 10})
    engagement_metrics = #{},       % Metrics such as likes, comments, shares (e.g., #{likes => 100, comments => 50})
    content_preferences = #{},      % Preferences for types of content (e.g., #{video => 60, text => 30})
    personality_traits = #{},       % Traits derived from user interactions (e.g., #{introvert => true, extrovert => false})
    social_graph_metrics = #{},     % Metrics related to the user’s social connections (e.g., #{connections_count => 150})
    content_creation_stats = #{},   % Statistics on user-generated content (e.g., #{posts_created => 50, likes_received => 200})
    feature_usage_stats = #{},      % Statistics on how different features of the platform are used (e.g., #{feature_x => 300, feature_y => 150})
    privacy_settings = #{},         % Privacy preferences and settings (e.g., #{profile_visibility => public, message_privacy => friends_only})
    accessibility_preferences = #{}, % Preferences related to accessibility (e.g., #{text_size => large, color_scheme => dark})
    notification_preferences = #{}, % User preferences for notifications (e.g., #{email => true, sms => false})
    third_party_integrations = #{}, % Information on third-party services integrated (e.g., #{google_drive => true, dropbox => false})
    % Stores activity patterns over time
    user_activity_patterns = #{
        %daily => [0, 0, 0, 0, 0, 0, 0],  % Activity levels per hour of the day
        %weekly => [1, 2, 3, 4, 5, 6, 7]   % Activity levels per day of the week
    },
    % Captures contextual information like location and current activity
    contextual_data = #{
        %location => {lat, lon},           % Current location coordinates (e.g., {37.7749, -122.4194})
        %current_activity => browsing      % Current activity (e.g., browsing, posting)
    },
    % Tracks interaction trends over time for analysis
    historical_interaction_trends = #{
        %daily => [{timestamp, interaction_count}],  % Daily interactions
        %weekly => [{week_number, interaction_count}] % Weekly interactions
    },
    % Engagement metrics for individual pieces of content
    content_engagement_metrics = #{
        %post_id => #{likes => 100, comments => 50, shares => 30} % Engagement metrics for a specific post
    },
    % Collects user feedback and ratings
    user_feedback = #{
        %feedback_id => #{rating => 5, comment => "Great feature!"} % Feedback on features or content
    },
    % Predictions related to user behavior
    behavioral_predictions = #{
        %future_engagement => 75,         % Predicted engagement level (e.g., 75%)
        %likelihood_of_churn => 0.1       % Likelihood of user churn (e.g., 10%)
    },
    % Performance metrics for AI models
    model_performance_metrics = #{
        %model_id => #{accuracy => 0.95, precision => 0.9, recall => 0.85} % Metrics for a specific model
    },
    % Sentiment analysis over different time periods
    user_sentiment_over_time = #{
        %daily => [{date, sentiment_score}],  % Daily sentiment scores
        %monthly => [{month, average_sentiment_score}] % Monthly average sentiment scores
    },
    % Custom attributes for flexible data storage
    custom_attributes = #{
        %custom_field_1 => value1, % Example custom field (e.g., favorite_color => blue)
        %custom_field_2 => value2  % Another custom field (e.g., favorite_genre => rock)
    },
    % Visualize engagement patterns using heatmaps
    engagement_heatmaps = #{
        %time_of_day => [0, 1, 2, 3, 4, 5, 6], % Engagement levels by hour
        %day_of_week => [1, 2, 3, 4, 5, 6, 7]  % Engagement levels by day of the week
    },

    feature_vectors = #{},      % Numerical representations of user features for ML models
    embedding_vectors = #{},    % User embeddings for various ML tasks
    cluster_assignments = #{},  % Results of clustering algorithms
    recommendation_history = [], % History of recommendations and their outcomes
    user_journey_stage, % Current stage in the user lifecycle (e.g., new, active, at_risk, churned)
    predictive_models = #{},    % Store model parameters or references for user-specific predictions
    anomaly_detection_scores = #{}, % Scores from anomaly detection algorithms
    natural_language_processing = #{
        sentiment_analysis => #{},
        topic_modeling => #{},
        entity_recognition => #{}
    },
    time_series_forecasts = #{}, % Time-based predictions for various user metrics
    reinforcement_learning_state = #{}, % State information for RL-based personalization
    multi_armed_bandit_data = #{}, % Data for exploration-exploitation trade-offs
    collaborative_filtering_data = #{}, % Data for collaborative filtering recommendations
    content_based_filtering_data = #{}, % Data for content-based recommendations
    similarity_scores = #{},    % Similarity to other users or items
    user_segmentation = #{},    % Results of various segmentation algorithms
    causal_inference_data = #{}, % Data for causal analysis of user behavior
    explainable_ai_outputs = #{}, % Human-readable explanations for AI decisions
    federated_learning_contributions = #{}, % User's contributions to federated learning models
    transfer_learning_adaptations = #{}, % Adaptations from transfer learning for this user
    meta_learning_parameters = #{}, % Meta-learning parameters for quick adaptation
    active_learning_queries = [], % Targeted queries for improving user models
    user_knowledge_graph = #{}, % Graph representation of user's knowledge and interests
    multimodal_data = #{},      % Integration of data from multiple modalities (text, image, video)
    cognitive_load_estimates = #{}, % Estimates of user's current cognitive load for adaptive UI
    attention_models = #{},     % Models of user attention for content prioritization
    trust_and_safety_scores = #{}, % Metrics related to user trustworthiness and safety
    augmented_reality_data = #{}, % Data for AR features
    virtual_reality_profile = #{}, % User profile for VR interactions
    voice_interaction_patterns = #{}, % Patterns in voice-based interactions
    biometric_data = #{}, % Securely stored biometric information
    iot_device_interactions = #{}, % Interactions with IoT devices
    blockchain_identity = #{}, % Decentralized identity information
    quantum_resistant_security = #{}, % Future-proof security measures
    neurofeedback_data = #{}, % Data from neurofeedback interactions
    emotional_intelligence_scores = #{}, % EQ-related metrics
    cultural_context_model = #{}, % Model of user's cultural background
    language_model_adaptation = #{}, % Personalized language model tweaks
    continual_learning_state = #{}, % State for ongoing learning about the user
    cross_platform_identity = #{}, % Linked identities across platforms
    ethical_ai_metrics = #{}, % Metrics ensuring ethical AI interactions
    data = #{}
}).

-record(ai_post, {
    id,
    post_id,
    sentiment_score = 0.0,         % Overall sentiment of the post (-1.0 to 1.0)
    topic_classification = [],     % List of topics the post is about
    content_category,              % Broad category of the content (e.g., news, personal, question)
    language,                      % Detected language of the post
    readability_score = 0.0,       % Measure of how easy the post is to read
    engagement_rate = 0.0,         % Calculated engagement rate of the post
    virality_score = 0.0,          % Measure of how viral the post is
    content_quality_score = 0.0,   % AI-generated score for content quality
    controversy_score = 0.0,       % Measure of how controversial the post is
    originality_score = 0.0,       % Measure of content originality
    user_segments = [],            % List of user segments this post appeals to
    ai_generated_tags = [],        % AI-generated tags describing the post
    entity_recognition = [],       % Named entities recognized in the post
    sentiment_distribution = #{},  % Detailed sentiment breakdown
    relevance_scores = #{},        % Relevance to different topics or interests
    content_warnings = [],         % AI-detected potential content warnings
    accessibility_metrics = #{},   % Metrics related to content accessibility
    seo_metrics = #{},             % Search engine optimization metrics
    related_posts = [],            % IDs of semantically related posts
    interaction_predictions = #{}, % Predicted interaction metrics
    ab_test_variant,               % If this post is part of an A/B test
    content_freshness_score = 0.0, % How fresh or timely the content is
    fact_check_results = #{},      % Results of automated fact-checking
    monetization_potential = 0.0,  % AI-estimated monetization potential
    content_summary,               % AI-generated summary of the post
    key_phrases = [],              % Important phrases extracted from the post
    image_analysis_results = #{},  % Results of AI analysis on post images
    video_analysis_results = #{},  % Results of AI analysis on post videos
    audio_analysis_results = #{},  % Results of AI analysis on post audio
    cross_platform_performance = #{}, % Metrics if shared on other platforms
    user_retention_impact = 0.0,   % Estimated impact on user retention
    content_lifecycle_stage,       % Stage of the content's lifecycle
    ai_recommended_actions = [],   % AI-suggested actions for the post
    embedding_vector = [],         % Numerical representation for ML models
    data = #{}
}).

-record(ai_chat, {
    id,
    chat_id,     % Reference back to the main chat record
    language_detected,            % The detected language of the message
    sentiment_score = 0.0,        % Overall sentiment of the message (-1.0 to 1.0)
    emotion_classification = [],  % List of detected emotions (e.g., [joy, anger, surprise])
    intent_classification,        % Classified intent of the message (e.g., question, statement, request)
    topic_classification = [],    % List of topics the message is about
    entity_recognition = [],      % Named entities recognized in the message
    key_phrases = [],             % Important phrases extracted from the message
    urgency_score = 0.0,          % How urgent the message is (0.0 to 1.0)
    toxicity_score = 0.0,         % Measure of how toxic/inappropriate the content is (0.0 to 1.0)
    privacy_sensitivity_score = 0.0, % How much sensitive information the message contains (0.0 to 1.0)
    conversation_context = [],    % List of relevant previous messages for context
    suggested_responses = [],     % AI-generated potential responses
    translation = #{},            % Translations of the message to other languages
    summarization,                % Brief AI-generated summary of the message
    clarity_score = 0.0,          % How clear and understandable the message is (0.0 to 1.0)
    engagement_score = 0.0,       % How likely the message is to elicit a response (0.0 to 1.0)
    conversation_flow_metrics = #{}, % Metrics about the overall conversation quality
    user_preferences_detected = [], % User likes/dislikes inferred from the conversation
    chat_bot_relevance_score = 0.0, % How well a chatbot could handle this message (0.0 to 1.0)
    spelling_grammar_corrections = [], % Suggested corrections for spelling and grammar
    message_importance_score = 0.0, % How important or critical the message is (0.0 to 1.0)
    conversation_stage,           % Current stage of the conversation (e.g., opening, ongoing, closing)
    next_action_prediction,       % Predicted next action in the conversation
    user_satisfaction_prediction = 0.0, % Predicted user satisfaction with the conversation (0.0 to 1.0)
    conversation_quality_score = 0.0, % Overall score of conversation effectiveness (0.0 to 1.0)
    message_embedding_vector = [], % Numerical representation of the message for ML models
    named_entity_linking = #{},   % Links recognized entities to a knowledge base
    speech_act_classification,    % Classification of the speech act (e.g., question, command, assertion)
    dialogue_act_classification,  % Classification of the dialogue act (e.g., greeting, farewell, clarification)
    sarcasm_detection_score = 0.0, % Likelihood that the message is sarcastic (0.0 to 1.0)
    humor_detection_score = 0.0,  % Likelihood that the message contains humor (0.0 to 1.0)
    formality_score = 0.0,        % How formal the message is (0.0 to 1.0)
    politeness_score = 0.0,       % How polite the message is (0.0 to 1.0)
    empathy_needed_score = 0.0,   % How much empathy is needed in the response (0.0 to 1.0)
    user_state_prediction = #{},  % Predicted user's current state (e.g., {mood: happy, stress_level: low})
    topic_derailment_score = 0.0, % How much the message deviates from the main topic (0.0 to 1.0)
    conversation_coherence_score = 0.0, % How well the conversation flows and makes sense (0.0 to 1.0)
    multilingual_analysis = #{},  % Analysis for messages containing multiple languages
    cross_cultural_appropriateness_score = 0.0, % How culturally appropriate the message is (0.0 to 1.0)
    message_retrieval_keywords = [], % Keywords for easier future retrieval of the message
    privacy_compliance_check = #{}, % Checks for compliance with privacy regulations
    sentiment_change_detection = 0.0, % Detected change in sentiment from previous messages (-1.0 to 1.0)
    conversation_milestones = [], % Important points or achievements in the conversation
    ai_confidence_score = 0.0,    % How confident the AI is in its analysis (0.0 to 1.0)
    human_in_the_loop_flag = false, % Indicates if human intervention might be needed
    real_time_feedback_suggestions = [], % Live suggestions for improving communication
    long_term_relationship_impact_score = 0.0, % Estimated impact on long-term user relationship (-1.0 to 1.0)
    last_updated,  % Timestamp of last AI analysis update
    model_version, % Version of AI model used for analysis
    data = #{}     % Additional custom data field for future expansions
}).

-record(ai_media, {
    id,
    media_id,     % Reference back to the main media record
    media_type,   % 'video' or 'audio'
    
    % General AI analysis
    content_classification = [],  % List of content categories (e.g., [landscape, portrait, meme])
    nsfw_score = 0.0,             % Likelihood of Not Safe For Work content (0.0 to 1.0)
    aesthetic_score = 0.0,        % AI-judged aesthetic quality (0.0 to 1.0)
    originality_score = 0.0,      % Measure of content originality (0.0 to 1.0)
    engagement_prediction = 0.0,  % Predicted user engagement level (0.0 to 1.0)
    
    % Image-specific analysis (for image files)
    image_analysis = #{
        object_detection => [],     % List of detected objects with bounding boxes
        scene_recognition => [],    % List of recognized scenes or settings
        facial_analysis => #{},     % Detailed facial feature analysis
        color_palette => [],        % Dominant colors in the image
        image_quality_metrics => #{}, % Metrics like sharpness, brightness, contrast
        text_in_image => [],        % Detected and recognized text in the image
        landmark_detection => [],   % Recognized landmarks or notable locations
        style_classification => [], % Artistic style classification (e.g., impressionist, abstract)
        image_sentiment => 0.0,     % Overall sentiment conveyed by the image (-1.0 to 1.0)
        composition_analysis => #{} % Analysis of image composition and framing
    },
    
    % Video-specific analysis (for video files)
    video_analysis = #{
        scene_segmentation => [],   % Timestamps of different scenes in the video
        action_recognition => [],   % Recognized actions or activities in the video
        object_tracking => #{},     % Tracked objects across video frames
        keyframe_extraction => [],  % Important frames extracted from the video
        video_summary => "",        % AI-generated summary of the video content
        emotional_arc => [],        % Emotional progression throughout the video
        visual_style_classification => [], % Visual style of the video (e.g., minimalist, vibrant)
        shot_type_analysis => [],   % Analysis of shot types used (e.g., close-up, wide shot)
        camera_motion_analysis => [], % Detected camera movements
        visual_effects_detection => [], % Detected visual effects or transitions
        color_scheme_analysis => [], % Overall color scheme and mood
        logo_brand_detection => [], % Detected logos or brands in the video
        on_screen_text_recognition => [], % Text appearing in the video
        celebrity_recognition => [] % Recognized celebrities or public figures (if applicable)
    },
    
    % Audio analysis (for both video and audio files)
    audio_analysis = #{
        speech_to_text => "",       % Transcribed speech from the audio
        speaker_diarization => [],  % Identification of different speakers
        audio_event_detection => [], % Detected audio events or sounds
        music_genre_classification => [], % Identified music genres
        audio_sentiment_analysis => 0.0, % Overall sentiment of the audio (-1.0 to 1.0)
        language_identification => "", % Identified language(s) in the audio
        audio_quality_metrics => #{}, % Metrics like noise level, clarity
        beat_detection => [],      % Detected beat timestamps
        tempo_analysis => 0.0,     % Beats per minute
        key_detection => "",       % Musical key of the audio
        instrument_recognition => [], % Recognized musical instruments
        vocal_analysis => #{},     % Analysis of vocal performances
        audio_segmentation => [],  % Segmentation of audio into distinct parts
        chorus_detection => [],    % Timestamps of detected choruses
        mood_classification => [], % Mood or emotion conveyed by the audio
        audio_fingerprinting => "" % Unique audio fingerprint for identification
    },
    
    % Deep learning features
    feature_embeddings = [],       % High-dimensional feature representation
    similarity_vectors = [],       % Vectors for content-based similarity search
    style_transfer_compatibility = 0.0, % Suitability for AI style transfer (0.0 to 1.0)
    
    % Machine learning predictions
    popularity_prediction = 0.0,   % Predicted popularity score (0.0 to 1.0)
    recommended_tags = [],         % AI-suggested tags for the media
    content_moderation_flags = [], % Potential issues flagged by AI moderation
    
    % Neural network analysis
    neural_style_classification = "", % Style classification using neural networks
    generative_ai_prompts = [],    % Suggested prompts for generative AI based on this media
    
    % AI-enhanced metadata
    ai_generated_caption = "",     % AI-generated description of the media
    semantic_segmentation = #{},   % Pixel-wise classification of image contents
    depth_estimation = #{},        % Estimated depth map for images or video frames
    three_d_reconstruction_potential = 0.0, % Suitability for 3D reconstruction (0.0 to 1.0)
    
    % Technical analysis
    file_integrity_check = "",     % Result of AI-powered file integrity analysis
    compression_artifacts_detection = 0.0, % Detected level of compression artifacts (0.0 to 1.0)
    metadata_consistency_score = 0.0, % Consistency of metadata with content (0.0 to 1.0)
    
    % Contextual analysis
    contextual_relevance_score = 0.0, % Relevance to current trends or events (0.0 to 1.0)
    cross_cultural_interpretation = #{}, % How the content might be perceived in different cultures
    
    % Accessibility features
    accessibility_score = 0.0,     % Overall accessibility of the media (0.0 to 1.0)
    alt_text_suggestion = "",      % AI-generated alternative text for images
    
    % Legal and ethical analysis
    copyright_infringement_probability = 0.0, % Likelihood of copyright issues (0.0 to 1.0)
    ethical_concerns = [],         % Potential ethical issues detected by AI
    
    model_version,                 % Version of AI model(s) used for analysis
    last_updated,                  % Timestamp of last AI analysis update
    confidence_scores = #{},       % Confidence levels for various AI predictions
    processing_time = 0.0,         % Time taken for AI analysis in seconds
    data = #{}                     % Additional custom data for future expansions
}).

-record(ai_notif, {
    id,
    notif_id,     % Reference back to the main notif record

    % Notification Classification
    notif_type,   % e.g., follow, like, comment, mention, system_alert
    priority_score = 0.0,  % AI-determined importance (0.0 to 1.0)
    
    % Content Analysis
    sentiment_score = 0.0, % Sentiment of the notification message (-1.0 to 1.0)
    emotion_classification = [], % e.g., [excitement, gratitude, curiosity]
    key_entities = [],     % Important entities mentioned in the notification
    
    % User Interaction Prediction
    click_through_probability = 0.0, % Likelihood of user interaction (0.0 to 1.0)
    expected_response_time = 0,  % Predicted time until user interaction (in seconds)
    
    % Personalization
    user_interest_alignment = 0.0, % How well it aligns with user interests (0.0 to 1.0)
    personalized_importance = 0.0, % Importance based on user history (0.0 to 1.0)
    
    % Timing Optimization
    optimal_delivery_time = {0,0,0}, % AI-suggested best time to show the notification
    time_sensitivity_score = 0.0, % How time-sensitive the notification is (0.0 to 1.0)
    
    % Context Awareness
    user_context = #{},    % e.g., #{location: "home", activity: "relaxing"}
    device_context = "",   % e.g., "mobile", "desktop", "tablet"
    
    % Notification Grouping
    group_id = "",         % ID for grouping related notifications
    group_position = 0,    % Position within the group (0 for standalone)
    
    % Language Optimization
    language_style = "",   % e.g., "formal", "casual", "emoji-rich"
    localization_needed = false, % Whether the message needs translation
    
    % Rich Media Suggestions
    suggested_media = #{}, % e.g., #{type: "image", url: "..."}
    
    % Accessibility
    accessibility_score = 0.0, % How accessible the notification is (0.0 to 1.0)
    alt_text_suggestion = "", % For any media in the notification
    
    % Feedback Loop
    user_response = "",    % e.g., "clicked", "ignored", "snoozed"
    feedback_score = 0.0,  % User-provided feedback if any (-1.0 to 1.0)
    
    % Anti-Spam and Safety
    spam_probability = 0.0, % Likelihood of being spam (0.0 to 1.0)
    safety_check_result = "", % e.g., "safe", "potential_harm", "blocked"
    
    % Engagement Metrics
    cumulative_views = 0,  % Number of times the notification was viewed
    engagement_score = 0.0, % Overall engagement metric (0.0 to 1.0)
    
    % A/B Testing
    ab_test_group = "",    % If this notification is part of an A/B test
    
    % Dynamic Content
    dynamic_content_placeholders = #{}, % For personalized content insertion
    
    % Cross-Platform Consistency
    cross_platform_id = "", % For consistent notification across devices
    
    % Privacy and Permissions
    privacy_level = "",    % e.g., "public", "followers_only", "private"
    required_permissions = [], % Any permissions needed to show full content
    
    % AI Model Metadata
    model_version,         % Version of AI model used for analysis
    confidence_score = 0.0, % AI's confidence in its analysis (0.0 to 1.0)
    processing_timestamp,  % When the AI analysis was performed
    
    data = #{}             % Additional custom data for future expansions
}).

-record(ai_comment, {
    id,
    comment_id,    % Reference back to the main comment record
    
    % Content Analysis
    sentiment_score = 0.0,         % Overall sentiment of the comment (-1.0 to 1.0)
    emotion_classification = [],   % e.g., [joy, anger, surprise]
    topic_classification = [],     % Main topics discussed in the comment
    key_phrases = [],              % Important phrases extracted from the comment
    entity_recognition = [],       % Named entities mentioned in the comment
    language_detected = "",        % Detected language of the comment
    toxicity_score = 0.0,          % Measure of how toxic/inappropriate the content is (0.0 to 1.0)
    
    % Engagement Prediction
    engagement_score = 0.0,        % Predicted engagement level (0.0 to 1.0)
    reply_probability = 0.0,       % Likelihood of receiving a reply (0.0 to 1.0)
    viral_potential = 0.0,         % Potential for the comment to go viral (0.0 to 1.0)
    
    % User Interaction
    user_mention_count = 0,        % Number of user mentions in the comment
    hashtag_count = 0,             % Number of hashtags used
    url_count = 0,                 % Number of URLs in the comment
    
    % Contextual Relevance
    relevance_to_post = 0.0,       % How relevant the comment is to the original post (0.0 to 1.0)
    conversation_depth = 0,        % Depth in the conversation thread
    
    % User Behavior Analysis
    author_credibility_score = 0.0, % Credibility score of the comment author (0.0 to 1.0)
    author_engagement_history = #{}, % Historical engagement metrics of the author
    
    % Moderation Assistance
    moderation_flags = [],         % Potential issues flagged for moderation
    auto_moderation_action = "",   % Suggested auto-moderation action if any
    
    % Enhanced Features
    sentiment_progression = [],    % Sentiment change if it's a long comment
    readability_score = 0.0,       % How easy the comment is to read (0.0 to 1.0)
    novelty_score = 0.0,           % How novel the comment is compared to others (0.0 to 1.0)
    
    % Recommendation Engine Data
    recommendation_vector = [],    % For use in recommendation systems
    
    % Accessibility
    accessibility_score = 0.0,     % How accessible the comment is (0.0 to 1.0)
    alt_text_suggestions = #{},    % For any media in the comment
    
    % Privacy and Safety
    pii_detection_results = #{},   % Detected Personal Identifiable Information
    safety_classification = "",    % e.g., "safe", "sensitive", "unsafe"
    
    % AI Model Metadata
    model_version,                 % Version of AI model used for analysis
    confidence_score = 0.0,        % AI's confidence in its analysis (0.0 to 1.0)
    processing_timestamp,          % When the AI analysis was performed
    
    data = #{}                     % Additional custom data for future expansions
}).

-record(ai_like, {
    id,
    like_id,      % Reference back to the main like record
    
    % User Behavior Analysis
    user_engagement_score = 0.0,   % Overall engagement score of the user (0.0 to 1.0)
    user_activity_frequency = 0.0, % How often the user interacts (likes per day)
    user_preference_vector = [],   % Vector representing user's content preferences
    
    % Context Analysis
    time_since_post_creation = 0,  % Time between post creation and like (in seconds)
    user_post_relationship = "",   % e.g., "follower", "friend", "new_interaction"
    session_engagement_level = 0.0, % User's engagement level in the current session
    
    % Predictive Metrics
    influence_score = 0.0,         % Predicted influence of this like on post visibility
    chain_reaction_probability = 0.0, % Likelihood of triggering more likes
    
    % Content Relevance
    content_category_alignment = 0.0, % How well the post aligns with user's interests
    trending_topic_relevance = 0.0,  % Relevance to current trending topics
    
    % User Journey
    user_lifecycle_stage = "",     % e.g., "new_user", "active", "re_engaged"
    retention_impact_score = 0.0,  % Predicted impact on user retention
    
    % Platform Health
    authenticity_score = 0.0,      % Likelihood that the like is genuine (not bot/spam)
    community_health_impact = 0.0, % Impact on overall community engagement health
    
    % Recommendation Engine Data
    recommendation_feedback = #{}, % How this like affects future recommendations
    
    % A/B Testing
    ab_test_group = "",            % If this like is part of an A/B test
    
    % Timing Analysis
    time_of_day_pattern = "",      % User's liking pattern by time of day
    day_of_week_pattern = "",      % User's liking pattern by day of week
    
    % Cross-Platform Data
    cross_platform_consistency = 0.0, % Consistency with user's behavior on other platforms
    
    % AI Model Metadata
    model_version,                 % Version of AI model used for analysis
    confidence_score = 0.0,        % AI's confidence in its analysis (0.0 to 1.0)
    processing_timestamp,          % When the AI analysis was performed
    
    data = #{}                     % Additional custom data for future expansions
}).



-define(MSG_INSUFFICIENT_FUNDS, <<"Insufficient funds.">>).

-record(business, {
    id,
    user_id,                    % Reference to the associated user account
    ai_business_id,
    ads_id = [],
    company_name,
    industry,
    company_size,
    website,
    business_email,
    business_phone,
    tax_id,
    verification_status = false,
    business_type,              % e.g., "B2B", "B2C", "Nonprofit"
    founding_date,
    location = #{
        address => "",
        city => "",
        state => "",
        country => "",
        postal_code => "",
        geo_coordinates => {0.0, 0.0}  % {latitude, longitude}
    },
    operating_hours = [],       % List of operating hours for each day
    products_services = [],     % List of main products or services
    social_media_links = #{},   % Map of platform to URL
    business_description,
    logo_url,
    banner_url,
    followers_count = 0,
    following_count = 0,
    posts = [],                 % List of post IDs
    posts_count = 0,
    average_engagement_rate = 0.0,
    customer_support_email,
    payment_info = #{},         % Payment related information
    subscription_tier = "free", % e.g., "free", "premium", "enterprise"
    account_managers = [],      % List of user IDs who manage this account
    business_goals = [],        % List of business objectives on the platform
    date_created,
    date_updated,
    brand_colors = [],          % List of primary brand colors
    brand_voice_keywords = [],  % List of words describing the brand voice
    certifications = [],        % List of business certifications
    awards = [],                % List of received awards
    partnerships = [],          % List of partner business IDs
    sustainability_initiatives = [], % List of sustainability efforts
    corporate_values = [],      % List of core corporate values
    employee_count,
    annual_revenue,
    target_audience = [],       % List of target audience demographics
    content_calendar = #{},     % Planned content schedule
    crm_integration = "",       % Integration with CRM systems
    loyalty_program = #{},      % Details of customer loyalty program
    user_generated_content = [], % List of UGC post IDs
    virtual_events = [],        % List of virtual event details
    augmented_reality_experiences = [], % List of AR experience IDs
    chatbot_enabled = false,    % Whether a chatbot is active for this account
    blockchain_initiatives = [], % List of blockchain-related projects
    data_privacy_certifications = [], % List of data privacy certifications
    ai_powered_features_enabled = #{}, % Map of AI features enabled for this account
    social_responsibility_score = 0.0, % Score based on social initiatives
    innovation_index = 0.0,     % Score based on innovative practices
    customer_satisfaction_index = 0.0, % Overall customer satisfaction score
    crisis_management_plan = "", % Reference to crisis management strategy
    digital_asset_portfolio = [], % List of owned digital assets (e.g., NFTs)
    metaverse_presence = #{},   % Details of presence in virtual worlds
    carbon_footprint_data = #{}, % Carbon footprint tracking information
    diversity_inclusion_metrics = #{}, % D&I related metrics
    talent_acquisition_channels = [], % List of preferred recruitment channels
    knowledge_base_url = "",    % URL to company's knowledge base
    api_integrations = [],      % List of integrated third-party APIs
    virtual_reality_spaces = #{},      % VR spaces associated with the business
    voice_interaction_profile = #{},   % Voice interaction characteristics
    biometric_authentication_methods = [], % List of supported biometric auth methods
    iot_integration_points = #{},      % IoT devices and data integration details
    quantum_resistant_security_measures = [], % Advanced security protocols
    neurofeedback_enabled_services = [], % Services using neurofeedback
    emotional_intelligence_score = 0.0, % EQ score for the business
    cultural_adaptation_strategies = #{}, % Strategies for different cultural markets
    language_localization_status = #{}, % Status of content localization
    continual_learning_initiatives = [], % Ongoing learning and development programs
    cross_platform_presence = #{},     % Presence on various digital platforms
    ethical_ai_commitment = #{},       % Ethical AI usage commitments and metrics
    data = #{} 
}).

-record(ai_business, {
    id,
    business_id,        % Reference to the main business_account record
    industry_vector = [],       % Numerical representation of the industry for ML models
    content_strategy = #{
        optimal_posting_times => [],
        recommended_content_types => [],
        audience_preferences => #{},
        viral_potential_predictor => #{},
        content_freshness_score => 0.0
    },
    audience_insights = #{
        demographics => #{},
        interests => [],
        behavior_patterns => #{},
        psychographic_profiles => [],
        customer_lifetime_value_predictions => #{}
    },
    competitor_analysis = #{
        similar_accounts => [],
        performance_benchmarks => #{},
        share_of_voice => 0.0,
        competitive_advantage_score => 0.0
    },
    sentiment_analysis = #{
        overall_brand_sentiment => 0.0,
        sentiment_trends => [],
        real_time_sentiment_tracker => #{},
        crisis_detection_alerts => []
    },
    growth_predictions = #{
        followers_growth_rate => 0.0,
        engagement_growth_rate => 0.0,
        revenue_forecast => #{},
        market_expansion_opportunities => []
    },
    content_performance_metrics = #{
        top_performing_posts => [],
        content_type_effectiveness => #{},
        ab_testing_results => [],
        multi_platform_performance_analysis => #{}
    },
    customer_feedback_analysis = #{
        common_praises => [],
        common_complaints => [],
        overall_satisfaction_score => 0.0,
        feedback_categorization => #{},
        trending_topics_in_feedback => []
    },
    market_trends = #{
        relevant_trending_topics => [],
        industry_specific_trends => [],
        predictive_trend_modeling => #{},
        early_adopter_identification => []
    },
    lead_generation_insights = #{
        lead_scoring_model => #{},
        conversion_funnel_analysis => #{},
        lead_nurturing_recommendations => [],
        ideal_customer_profile_generator => #{}
    },
    ai_powered_recommendations = #{
        content_ideas => [],
        engagement_strategies => [],
        growth_opportunities => [],
        product_development_suggestions => [],
        pricing_optimization_recommendations => []
    },
    brand_voice_analysis = #{
        tone_consistency_score => 0.0,
        key_brand_attributes => [],
        brand_voice_evolution_tracker => #{},
        cross_channel_consistency_analysis => #{}
    },
    campaign_performance_tracking = #{
        active_campaigns => [],
        historical_campaign_data => #{},
        roi_calculator => #{},
        cross_campaign_impact_analysis => #{}
    },
    ai_chatbot_configuration = #{
        trained_topics => [],
        response_templates => #{},
        escalation_criteria => [],
        sentiment_adaptive_responses => #{},
        multilingual_support_capabilities => []
    },
    personalization_engine = #{
        customer_segments => [],
        tailored_content_strategies => #{},
        dynamic_website_personalization => #{},
        individual_user_preference_models => #{}
    },
    fraud_detection_score = 0.0,
    business_health_index = 0.0,
    sustainability_score = 0.0,
    innovation_index = 0.0,
    collaboration_suggestions = [], % Potential business partners or collaborations
    market_position_analysis = #{
        strengths => [],
        weaknesses => [],
        opportunities => [],
        threats => [],
        ai_generated_strategic_recommendations => []
    },
    ai_generated_business_insights = [], % Regular AI-generated business advice
    predictive_analytics = #{
        sales_forecasts => #{},
        churn_prediction_model => #{},
        product_trend_predictions => [],
        demand_forecasting => #{},
        price_elasticity_model => #{}
    },
    nlp_enhanced_customer_support = #{
        auto_categorized_queries => #{},
        suggested_responses => #{},
        sentiment_based_prioritization => #{},
        multilingual_support_quality => #{},
        customer_intent_prediction => #{}
    },
    visual_content_analysis = #{
        image_effectiveness_scores => #{},
        video_engagement_analytics => #{},
        brand_consistency_checker => #{},
        auto_generated_visual_content_ideas => []
    },
    social_listening_insights = #{
        brand_mentions_analysis => #{},
        industry_conversation_trends => [],
        influencer_identification => [],
        crisis_early_warning_system => #{}
    },
    regulatory_compliance_assistant = #{
        applicable_regulations => [],
        compliance_checklist => #{},
        risk_assessment_scores => #{},
        automated_report_generator => #{}
    },
    ecosystem_impact_analysis = #{
        supply_chain_sustainability_score => 0.0,
        community_impact_metrics => #{},
        ethical_business_practice_rating => 0.0
    },
    ai_driven_innovation_lab = #{
        emerging_technology_adoption_recommendations => [],
        disruptive_business_model_scenarios => [],
        future_proofing_strategies => []
    },
    talent_analytics = #{
        skill_gap_analysis => #{},
        employee_sentiment_predictor => #{},
        productivity_optimization_suggestions => []
    },
    digital_twin_modeling = #{
        business_process_simulations => [],
        what_if_scenario_analyses => [],
        predictive_maintenance_schedules => #{}
    },
    quantum_computing_readiness = #{
        potential_use_cases => [],
        implementation_roadmap => #{},
        expected_impact_assessment => #{}
    },
    augmented_reality_analytics = #{
        user_engagement_metrics => #{},
        feature_popularity_ranking => [],
        roi_assessment => #{}
    },
    virtual_reality_insights = #{
        user_behavior_patterns => #{},
        immersion_scores => #{},
        virtual_store_performance => #{}
    },
    voice_interaction_analytics = #{
        common_queries => [],
        sentiment_analysis => #{},
        accent_adaptation_metrics => #{}
    },
    biometric_data_utilization = #{
        authentication_success_rates => #{},
        fraud_prevention_effectiveness => 0.0
    },
    iot_data_insights = #{
        device_usage_patterns => #{},
        predictive_maintenance_schedules => #{},
        cross-device_behavior_analysis => #{}
    },
    blockchain_performance_metrics = #{
        transaction_volumes => #{},
        smart_contract_efficiency => #{},
        token_economy_health => 0.0
    },
    quantum_computing_applications = #{
        optimization_problems_solved => [],
        cryptography_enhancements => #{},
        simulation_accuracies => #{}
    },
    neurofeedback_effectiveness = #{
        user_satisfaction_scores => #{},
        behavioral_change_metrics => #{},
        health_outcome_improvements => #{}
    },
    emotional_intelligence_development = #{
        employee_eq_scores => #{},
        customer_interaction_quality => 0.0,
        leadership_empathy_metrics => #{}
    },
    cultural_context_adaptation = #{
        market_specific_strategies => #{},
        cultural_faux_pas_avoidance_rate => 0.0,
        localization_effectiveness => #{}
    },
    language_model_fine_tuning = #{
        dialect_adaptation_progress => #{},
        industry_jargon_mastery => #{},
        translation_accuracy_scores => #{}
    },
    continual_learning_progress = #{
        skill_acquisition_rates => #{},
        knowledge_retention_scores => #{},
        innovation_application_metrics => #{}
    },
    cross_platform_synergy = #{
        unified_brand_presence_score => 0.0,
        cross_platform_user_journey_maps => #{},
        omnichannel_experience_rating => 0.0
    },
    ethical_ai_impact = #{
        fairness_scores => #{},
        transparency_metrics => #{},
        accountability_measures => #{}
    },
    metaverse_engagement_analytics = #{
        virtual_event_attendance => #{},
        digital_asset_ownership => #{},
        virtual_economy_participation => #{}
    },
    data = #{}
}).

-record(ads, {
    id,
    ai_ads_id,
    user_id,
    business_account_id,        % ID of the business running the ad
    campaign_id,                % ID of the campaign this ad belongs to
    ad_type,                    % e.g., "image", "video", "carousel", "interactive", "augmented_reality"
    content = #{
        title => "",
        description => "",
        media_urls => [],       % URLs to images, videos, or other media
        call_to_action => ""    % e.g., "Shop Now", "Learn More", "Sign Up"
    },
    target_audience = #{
        demographics => #{},
        interests => [],
        behaviors => [],
        lookalike_audiences => []
    },
    budget = #{
        total_budget => 0,
        daily_budget => 0,
        currency => "USD"
    },
    schedule = #{
        start_date => "",
        end_date => "",
        time_targeting => []    % Specific times of day to show the ad
    },
    placement = #{
        platforms => [],        % e.g., ["mobile", "desktop", "tablet"]
        specific_locations => [] % e.g., "feed", "stories", "sidebar"
    },
    performance_metrics = #{
        impressions => 0,
        clicks => 0,
        conversions => 0,
        ctr => 0.0,             % Click-through rate
        cpc => 0.0,             % Cost per click
        roas => 0.0             % Return on ad spend
    },
    a_b_testing = #{
        variants => [],         % List of variant IDs
        winning_variant => ""
    },
    dynamic_content = #{
        personalization_rules => #{},
        content_variants => []
    },
    interactive_elements = #{
        polls => [],
        quizzes => [],
        mini_games => []
    },
    augmented_reality_features = #{
        ar_filter_url => "",
        ar_experience_type => ""
    },
    shoppable_features = #{
        product_tags => [],
        instant_checkout => false
    },
    compliance_check = #{
        approved => false,
        rejection_reasons => []
    },
    eco_friendly_badge = false, % For ads promoting sustainable products/services
    localization = #{},         % Translations and cultural adaptations
    accessibility_features = #{},% e.g., alt text, closed captions
    chatbot_integration = "",   % ID of associated chatbot for instant queries
    user_generated_content = [],% IDs of UGC incorporated in the ad
    social_proof_elements = [], % e.g., reviews, ratings, usage statistics
    sequential_storytelling_id = "", % For ads that tell a story across multiple exposures
    context_aware_adaptation = #{}, % Rules for adapting based on user context
    voice_assistant_integration = #{}, % For audio-based ad interactions
    blockchain_verification = "",  % For ad transparency and verification
    neuroscience_tested = false,   % Indicates if the ad was tested using neuromarketing techniques
    virtual_reality_components = #{
        vr_experience_url => "",
        vr_interaction_type => ""
    },
    voice_activated_elements = #{
        voice_commands => [],
        audio_branding => ""
    },
    biometric_response_tracking = #{
        enabled => false,
        metrics_tracked => []
    },
    iot_integration = #{
        compatible_devices => [],
        smart_home_actions => []
    },
    blockchain_verified_metrics = #{},
    quantum_resistant_encryption = false,
    neurofeedback_optimized = false,
    emotional_ai_integration = #{
        emotion_detection => false,
        adaptive_content => #{}
    },
    cultural_sensitivity_score = 0.0,
    language_localization = #{},
    continuous_learning_adaptation = #{
        version => "",
        last_updated => ""
    },
    cross_reality_experience = #{}, % Bridging AR, VR, and physical world
    ethical_ai_compliance = #{
        transparency_level => 0.0,
        fairness_score => 0.0
    },
    metaverse_ready = false,
    data = #{} 
}).

-record(ai_ads, {
    id,
    ads_id,           % Reference to the main advertisement record
    performance_prediction = #{
        estimated_reach => 0,
        predicted_ctr => 0.0,
        expected_roas => 0.0
    },
    audience_expansion_suggestions = [], % AI-suggested new audience segments
    content_optimization = #{
        suggested_improvements => [],
        optimal_content_length => 0,
        color_scheme_recommendations => []
    },
    sentiment_analysis = #{
        overall_sentiment => 0.0,
        sentiment_distribution => #{}
    },
    competitor_ad_analysis = #{
        similar_ads => [],
        differentiation_score => 0.0
    },
    trend_alignment_score = 0.0,  % How well the ad aligns with current trends
    viral_potential_score = 0.0,  % Likelihood of the ad going viral
    brand_safety_analysis = #{
        safety_score => 0.0,
        potential_issues => []
    },
    cross_platform_performance_prediction = #{},
    ai_generated_ad_variants = [], % Automatically generated ad variations
    real_time_bidding_insights = #{
        optimal_bid_suggestions => #{},
        auction_win_probability => 0.0
    },
    attention_heatmap = #{},    % Predicted user attention areas
    emotional_impact_prediction = #{
        primary_emotion => "",
        emotion_intensity => 0.0
    },
    contextual_relevance_engine = #{
        relevance_scores => #{},
        context_matching_rules => #{}
    },
    ad_fatigue_predictor = #{
        estimated_fatigue_curve => [],
        refresh_recommendations => []
    },
    personalization_effectiveness = #{
        personalization_impact_score => 0.0,
        individual_element_effectiveness => #{}
    },
    multi_touch_attribution_model = #{},
    incrementality_testing_insights = #{},
    customer_journey_position_optimizer = #{},
    dynamic_budget_allocation_suggestions = #{},
    creative_element_performance = #{}, % Performance breakdown of individual ad elements
    ai_powered_copywriting_suggestions = [],
    behavioral_economics_insights = #{},
    neuromarketing_alignment_score = 0.0,
    vr_engagement_analytics = #{
        immersion_score => 0.0,
        interaction_depth => 0.0,
        presence_metrics => #{}
    },
    voice_interaction_insights = #{
        voice_engagement_rate => 0.0,
        common_voice_queries => [],
        voice_sentiment_analysis => #{}
    },
    biometric_impact_assessment = #{
        arousal_levels => [],
        cognitive_load => 0.0,
        attention_patterns => #{}
    },
    iot_ecosystem_effectiveness = #{
        cross_device_impact => 0.0,
        smart_home_integration_score => 0.0
    },
    blockchain_transparency_metrics = #{
        verification_speed => 0.0,
        tamper_evidence_score => 0.0
    },
    quantum_computing_applications = #{
        optimization_areas => [],
        performance_improvement => 0.0
    },
    neurofeedback_enhancement_suggestions = [],
    emotion_ai_insights = #{
        emotion_journey_map => [],
        adaptive_content_effectiveness => 0.0
    },
    cultural_resonance_analysis = #{
        cultural_appropriateness_score => 0.0,
        cross_cultural_appeal_metrics => #{}
    },
    linguistic_optimization_insights = #{
        clarity_score => 0.0,
        persuasiveness_metrics => #{}
    },
    continual_learning_performance = #{
        adaptation_speed => 0.0,
        improvement_trajectory => []
    },
    cross_reality_engagement_metrics = #{
        seamless_transition_score => 0.0,
        cross_platform_consistency => 0.0
    },
    ethical_ai_impact_assessment = #{
        bias_mitigation_effectiveness => 0.0,
        fairness_across_demographics => #{}
    },
    metaverse_readiness_score = 0.0,
    predictive_long_term_brand_impact = #{
        brand_equity_forecast => [],
        long_term_roi_projection => 0.0
    },
    cognitive_load_optimization = #{
        information_density_score => 0.0,
        attention_efficiency_metrics => #{}
    },
    haptic_feedback_effectiveness = #{
        engagement_lift => 0.0,
        sensory_brand_association_strength => 0.0
    },
    data = #{}
}).
